### ISSUE TITLE
compiler error caused by XCGLogger

### ISSUE THREAD

**Issue by abigailyuan** [zetasq/Tinbox#1]
The project cannot be built within Xcode due to the old version of compiler that built XCGLogger framework. 

Requires rebuilding of XCGLogger.

**Comment by zetasq** [comment]
OK, I will update this project this weekend :) . Currently this app doesn't do or show anything after user login, I will also add today's events and tasks list ( task detail and event detail may take more time to accomplish). Thank you for feedback!

**Comment by zetasq** [comment]
I've update the project and change the main branch to master. Now the project can be built!
